#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/jwt_security
#    username: username
#    password: password
#    driver-class-name: org.postgresql.Driver
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


  mail:
    host: smtp.gmail.com #64.233.167.108
    port: 587
    username: agrimanagerplus@gmail.com
    password: mtsitzrxppkznrxk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#

#  jpa:
#
#
#database-platform: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days




